<?php

use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\Exception\RouteNotFoundException;
use Psr\Log\LoggerInterface;

/**
 * appDevUrlGenerator
 *
 * This class has been auto-generated
 * by the Symfony Routing Component.
 */
class appDevUrlGenerator extends Symfony\Component\Routing\Generator\UrlGenerator
{
    private static $declaredRoutes = array(
        '_wdt' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:toolbarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_wdt',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_home' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:homeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_bar' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchBarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/search_bar',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_purge' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:purgeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/purge',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_info' => array (  0 =>   array (    0 => 'about',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:infoAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'about',    ),    1 =>     array (      0 => 'text',      1 => '/_profiler/info',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_phpinfo' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:phpinfoAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/phpinfo',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_search_results' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:searchResultsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/search/results',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_router' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.router:panelAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/router',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_exception_css' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.exception:cssAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/exception.css',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    2 =>     array (      0 => 'text',      1 => '/_profiler',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_configurator_home' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sensio\\Bundle\\DistributionBundle\\Controller\\ConfiguratorController::checkAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_configurator/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_configurator_step' => array (  0 =>   array (    0 => 'index',  ),  1 =>   array (    '_controller' => 'Sensio\\Bundle\\DistributionBundle\\Controller\\ConfiguratorController::stepAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'index',    ),    1 =>     array (      0 => 'text',      1 => '/_configurator/step',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_configurator_final' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Sensio\\Bundle\\DistributionBundle\\Controller\\ConfiguratorController::finalAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_configurator/final',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_twig_error_test' => array (  0 =>   array (    0 => 'code',    1 => '_format',  ),  1 =>   array (    '_controller' => 'twig.controller.preview_error:previewErrorPageAction',    '_format' => 'html',  ),  2 =>   array (    'code' => '\\d+',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '.',      2 => '[^/]++',      3 => '_format',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '\\d+',      3 => 'code',    ),    2 =>     array (      0 => 'text',      1 => '/_error',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_manager' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::managerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node/manager',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_show' => array (  0 =>   array (    0 => 'category',    1 => 'slug',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '.html',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/\\.]++',      3 => 'slug',    ),    2 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'category',    ),    3 =>     array (      0 => 'text',      1 => '/node/show',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::createAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/node',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_update' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::updateAction',  ),  2 =>   array (    '_method' => 'POST|PUT',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/update',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/node',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::deleteAction',  ),  2 =>   array (    '_method' => 'POST|DELETE',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/node',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_delete_photo' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\GalleryController::deletePhotoAction',  ),  2 =>   array (    '_method' => 'post|delete',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/node/delete_photo',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_attach_load' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\GalleryController::loadAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node/load',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_show_page' => array (  0 =>   array (    0 => 'slug',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::showAction',    'category' => 1,  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '.html',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/\\.]++',      3 => 'slug',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_show_blog_page' => array (  0 =>   array (    0 => 'slug',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeController::showAction',    'category' => 2,  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '.html',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/\\.]++',      3 => 'slug',    ),    2 =>     array (      0 => 'text',      1 => '/blog',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_show_blog' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::showAction',    'slug' => 'blog',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/blog',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_manager' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::managerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node_cat/manager',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node_cat/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::createAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/node_cat/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/node_cat',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_update' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::updateAction',  ),  2 =>   array (    '_method' => 'POST|PUT',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/update',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/node_cat',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::deleteAction',  ),  2 =>   array (    '_method' => 'POST|DELETE',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/node_cat',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'node_cat_show' => array (  0 =>   array (    0 => 'slug',  ),  1 =>   array (    '_controller' => 'Core\\NodeBundle\\Controller\\NodeCategoryController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'slug',    ),    1 =>     array (      0 => 'text',      1 => '/node_cat',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'core_notification_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\CoreBundle\\Controller\\NotificationController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/notification/show',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'site_setting' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\CoreBundle\\Controller\\SettingController::indexAction',  ),  2 =>   array (    '_method' => 'POST|GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/setting',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_profile_show' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ProfileController::showAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_profile_edit' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ProfileController::editAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_register' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\RegistrationController::registerAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\RegistrationController::checkEmailAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_confirm' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\RegistrationController::confirmAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/register/confirm',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_registration_confirmed' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\RegistrationController::confirmedAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/register/confirmed',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_request' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::requestAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/request',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_send_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::sendEmailAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/send-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_check_email' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::checkEmailAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/resetting/check-email',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_resetting_reset' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ResettingController::resetAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/resetting/reset',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_change_password' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\ChangePasswordController::changePasswordAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/profile/change-password',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_security_login' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\SecurityController::loginAction',  ),  2 =>   array (    '_method' => 'GET|POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_security_check' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\SecurityController::checkAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/login_check',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_user_security_logout' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'FOS\\UserBundle\\Controller\\SecurityController::logoutAction',  ),  2 =>   array (    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/logout',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/category/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/category/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::createAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/category/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/category',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory_update' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::updateAction',  ),  2 =>   array (    '_method' => 'POST|PUT',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/update',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/category',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::deleteAction',  ),  2 =>   array (    '_method' => 'POST|DELETE',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/category',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory_levelmanager' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::levelManagerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/category/level_manager',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adcategory_show' => array (  0 =>   array (    0 => 'slug',    1 => 'child_slug',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdCategoryController::showAction',    'child_slug' => NULL,  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'child_slug',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'slug',    ),    2 =>     array (      0 => 'text',      1 => '/category',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_manager' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::managerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/manager',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_favorite' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::favoriteAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/favorite',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_show' => array (  0 =>   array (    0 => 'slug',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '.html',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/\\.]++',      3 => 'slug',    ),    2 =>     array (      0 => 'text',      1 => '/ad',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::newAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::createAction',  ),  2 =>   array (    '_method' => 'post',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_create_load_category' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::CategoryLoadAction',  ),  2 =>   array (    '_method' => 'post',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/load_category',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::editAction',  ),  2 =>   array (    '_method' => 'post|put|get',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/edit',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/ad',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_delete' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::deleteAction',  ),  2 =>   array (    '_method' => 'post|delete',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/ad',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::searchAction',  ),  2 =>   array (    '_method' => 'get',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_delete_photo' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::deletePhotoAction',  ),  2 =>   array (    '_method' => 'post|delete',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/ad/delete_photo',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'adtask_list' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdTaskController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/task/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_sale' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\SaleController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad_order/sale',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_sale_stat' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\SaleController::statAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad_order/sale/stat',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_sale_services' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\SaleController::servicesAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad_order/sale/services',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_sale_finances' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\SaleController::financesAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad_order/sale/finances',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_create' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdOrderController::createAction',  ),  2 =>   array (    '_method' => 'post',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad_order/create',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_pay' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdOrderController::payAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/ad_order/pay',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_finish' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdOrderController::finishAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/ad_order/finish/revise',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_remove' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdOrderController::removeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '.html',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/\\.]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/ad_order/remove',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_adopt' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdOrderController::adoptAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '.html',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/\\.]++',      3 => 'id',    ),    2 =>     array (      0 => 'text',      1 => '/ad_order/adopt',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order_show' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdOrderController::showAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/ad_order',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_order' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdOrderController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad_order/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'ad_favorite_add' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdFavoriteController::addOrRemoveAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/ad/favorite/addOrRemove.json',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'core_index' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\AdBundle\\Controller\\AdController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'msg_create_dialog' => array (  0 =>   array (    0 => 'recipient',  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::createDialogAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'recipient',    ),    1 =>     array (      0 => 'text',      1 => '/message/create_dialog',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'msg_get_messages' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::getMessagesAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/message/get_messages',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_balance_replenish' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\BalanceController::replenishAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/user/balance/replenish',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_page' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\UserController::indexAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/id',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_settings_page' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\UserController::settingsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/settings',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_dashboard' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\UserController::dashBoardAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/user/dashboard',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'users_manager' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\UserController::managerAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/user/manager',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\UserController::editAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/user/edit',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_stat' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\UserController::statAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/user/stat',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'user_settings_edit' => array (  0 =>   array (    0 => 'id',  ),  1 =>   array (    '_controller' => 'Core\\UserBundle\\Controller\\UserController::editSettingsAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'id',    ),    1 =>     array (      0 => 'text',      1 => '/user/editAdminSettings',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'liip_imagine_filter_runtime' => array (  0 =>   array (    0 => 'filter',    1 => 'hash',    2 => 'path',  ),  1 =>   array (    '_controller' => 'liip_imagine.controller:filterRuntimeAction',  ),  2 =>   array (    'filter' => '[A-z0-9_\\-]*',    'path' => '.+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '.+',      3 => 'path',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'hash',    ),    2 =>     array (      0 => 'text',      1 => '/rc',    ),    3 =>     array (      0 => 'variable',      1 => '/',      2 => '[A-z0-9_\\-]*',      3 => 'filter',    ),    4 =>     array (      0 => 'text',      1 => '/media/cache/resolve',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'liip_imagine_filter' => array (  0 =>   array (    0 => 'filter',    1 => 'path',  ),  1 =>   array (    '_controller' => 'liip_imagine.controller:filterAction',  ),  2 =>   array (    'filter' => '[A-z0-9_\\-]*',    'path' => '.+',    '_method' => 'GET',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '.+',      3 => 'path',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[A-z0-9_\\-]*',      3 => 'filter',    ),    2 =>     array (      0 => 'text',      1 => '/media/cache/resolve',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_inbox' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::inboxAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/message/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_sent' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::sentAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/message/sent',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_deleted' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::deletedAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/message/deleted',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_search' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::searchAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/message/search',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_thread_new' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::newThreadAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/message/new',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_thread_delete' => array (  0 =>   array (    0 => 'threadId',  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::deleteAction',  ),  2 =>   array (    '_method' => 'POST|DELETE',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/delete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'threadId',    ),    2 =>     array (      0 => 'text',      1 => '/message',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_thread_undelete' => array (  0 =>   array (    0 => 'threadId',  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::undeleteAction',  ),  2 =>   array (    '_method' => 'POST',  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/undelete',    ),    1 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'threadId',    ),    2 =>     array (      0 => 'text',      1 => '/message',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_message_thread_view' => array (  0 =>   array (    0 => 'threadId',  ),  1 =>   array (    '_controller' => 'Core\\MessageBundle\\Controller\\MessageController::threadAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'threadId',    ),    1 =>     array (      0 => 'text',      1 => '/message',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        'fos_js_routing_js' => array (  0 =>   array (    0 => '_format',  ),  1 =>   array (    '_controller' => 'fos_js_routing.controller:indexAction',    '_format' => 'js',  ),  2 =>   array (    '_format' => 'js|json',  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '.',      2 => 'js|json',      3 => '_format',    ),    1 =>     array (      0 => 'text',      1 => '/js/routing',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
    );

    /**
     * Constructor.
     */
    public function __construct(RequestContext $context, LoggerInterface $logger = null)
    {
        $this->context = $context;
        $this->logger = $logger;
    }

    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }

        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];

        return $this->doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, $requiredSchemes);
    }
}
