<?php

namespace Proxies\__CG__\Core\NodeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Node extends \Core\NodeBundle\Entity\Node implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'id', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'category', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'views', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'userCreate', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'title', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'dateCreated', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'dateUpdated', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'slug', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'main', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'short_main');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'id', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'category', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'views', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'userCreate', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'title', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'dateCreated', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'dateUpdated', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'slug', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'main', '' . "\0" . 'Core\\NodeBundle\\Entity\\Node' . "\0" . 'short_main');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Node $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setViews($views)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViews', array($views));

        return parent::setViews($views);
    }

    /**
     * {@inheritDoc}
     */
    public function getViews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViews', array());

        return parent::getViews();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($dateCreated));

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdated($dateUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdated', array($dateUpdated));

        return parent::setDateUpdated($dateUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdated', array());

        return parent::getDateUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setMain($main)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMain', array($main));

        return parent::setMain($main);
    }

    /**
     * {@inheritDoc}
     */
    public function getMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMain', array());

        return parent::getMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortMain($shortMain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortMain', array($shortMain));

        return parent::setShortMain($shortMain);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortMain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortMain', array());

        return parent::getShortMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Core\NodeBundle\Entity\NodeCategory $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreate(\Core\UserBundle\Entity\User $userCreate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreate', array($userCreate));

        return parent::setUserCreate($userCreate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreate', array());

        return parent::getUserCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function getImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg', array());

        return parent::getImg();
    }

}
